language: csharp
solution: Infinity.sln
sudo: false

mono:
 - 3.12.0

script:
 - xbuild /p:Configuration=Release Infinity.sln
 - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./Infinity.Tests/bin/Release/Infinity.Tests.dll

branches:
   only:
   - master

notifications:
   recipients:
   - ethomson@edwardthomson.com
   email:
      on_success: change
      on_failure: always
